version: '3'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    #environment:
    #  - DB_HOST=db
    #  - DB_DATABASE=laravel
    #  - DB_USERNAME=root
    #  - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    entrypoint: dockerize -template ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf nginx -g "daemon off;"
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=9000
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  redis:
    image:
      redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  db:
    image:
      mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
